cask_args appdir: "/Applications"

brew "git"
brew "rbenv"
brew "rbenv-default-gems"
brew "pyenv"
brew "nodebrew"
brew "yarn", args: ["without-node"]
brew "jq"
brew "postgresql"
brew "packer"

cask "slack"
cask "google-chrome"
cask "google-japanese-ime"
cask "dash"
cask "visual-studio-code"
cask "gitkraken"
cask "docker"
cask "chefdk"
cask "caffeine"
cask "near-lock"
cask "day-o"
